# classes/data_manager.py
class DataManager:
    def __init__(self):
        self.data = {
            "원": [
                {"name": "삼성전자", "price": 20},
                {"name": "LG화학", "price": 30},
                {"name": "NAVER", "price": 5},
                {"name": "카카오", "price": 10},
                {"name": "현대차", "price": 25},
                {"name": "기아", "price": 15},
                {"name": "셀트리온", "price": 2},
                {"name": "POSCO홀딩스", "price": 40},
                {"name": "SK하이닉스", "price": 120},
                {"name": "두산에너빌리티", "price": 8},
                {"name": "한화솔루션", "price": 10},
                {"name": "HMM", "price": 2},
                {"name": "롯데케미칼", "price": 5},
                {"name": "KT", "price": 6},
                {"name": "CJ제일제당", "price": 1},
                {"name": "LG이노텍", "price": 1},
                {"name": "대한항공", "price": 2},
                {"name": "아모레퍼시픽", "price": 12},
                {"name": "S-OIL", "price": 9},
                {"name": "삼성바이오로직스", "price": 150},
            ],
            "코인": [
                {"name": "비트코인", "price": 950},
                {"name": "이더리움", "price": 65},
                {"name": "리플", "price": 0.0072},
                {"name": "솔라나", "price": 1.9},
                {"name": "도지코인", "price": 0.0185},
                {"name": "폴카닷", "price": 0.72},
                {"name": "체인링크", "price": 2.15},
                {"name": "에이다", "price": 0.082},
                {"name": "아발란체", "price": 4.7},
                {"name": "라이트코인", "price": 9.8},
                {"name": "이오스", "price": 0.115},
                {"name": "트론", "price": 0.0180},
                {"name": "비트코인캐시", "price": 52},
                {"name": "스텔라", "price": 0.017},
                {"name": "테조스", "price": 0.1100},
                {"name": "샌드박스", "price": 0.052},
                {"name": "디센트럴랜드", "price": 0.072},
                {"name": "APE", "price": 0.21},
                {"name": "FTM", "price": 0.0450},
                {"name": "ARBITRUM", "price": 0.15},
            ],
            "금": [
                {"name": "금괴 1kg", "price": 75},
                {"name": "금화", "price": 72},
                {"name": "은괴 1kg", "price": 0.95},
                {"name": "백금", "price": 43},
                {"name": "팔라듐", "price": 82},
                {"name": "로듐", "price": 1500},
                {"name": "금반지", "price": 320},
                {"name": "금목걸이", "price": 620},
                {"name": "금시계", "price": 1350},
                {"name": "은화", "price": 55},
                {"name": "금은혼합", "price": 31},
                {"name": "금장식품", "price": 270},
                {"name": "금수저세트", "price": 450},
                {"name": "금메달", "price": 550},
                {"name": "은메달", "price": 120},
                {"name": "금조각", "price": 15},
                {"name": "금괴 10g", "price": 950},
                {"name": "금괴 100g", "price": 9500},
                {"name": "금괴 500g", "price": 47500},
                {"name": "금괴 5kg", "price": 475000},
            ],
            "스탁": [
                {"name": "APPLE", "price": 220},
                {"name": "TESLA", "price": 260},
                {"name": "NVIDIA", "price": 1140},
                {"name": "GOOGLE", "price": 160},
                {"name": "MICROSOFT", "price": 420},
                {"name": "META", "price": 330},
                {"name": "AMAZON", "price": 185},
                {"name": "NETFLIX", "price": 490},
                {"name": "INTEL", "price": 45},
                {"name": "AMD", "price": 118},
                {"name": "IBM", "price": 162},
                {"name": "ORACLE", "price": 142},
                {"name": "BROADCOM", "price": 1450},
                {"name": "ADOBE", "price": 600},
                {"name": "ASML", "price": 890},
                {"name": "TSMC", "price": 120},
                {"name": "DISNEY", "price": 95},
                {"name": "SONY", "price": 91},
                {"name": "QUALCOMM", "price": 175},
                {"name": "CISCO", "price": 54},
            ]
        }

    def get_category_data(self, category):
        return self.data.get(category, [])
